login_task/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from .views import *

urlpatterns = [
    path('signup/', UserCreateAndLoginView.as_view(), name='signup'),
    path('login/', LoginView.as_view(
        redirect_authenticated_user=True,
        template_name='accounts/login.html'
    ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user_detail/<int:pk>/', UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', UserUpdate.as_view(), name='user_update'),
    path('user_delete/<int:pk>/', UserDelete.as_view(), name='user_delete'),
    path('password_change/', PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDone.as_view(), name='password_change_done'),
]

login_task/django_login/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('accounts/', include('accounts.urls')),
]

login_task/tasks/urls.py
from django.urls import path
from . import views
app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('detail/<int:task_id>', views.detail, name='detail'),
    path('edit/<int:task_id>', views.edit, name='edit'),
    path('delete/<int:task_id>', views.delete, name='delete'),
]

login_task/accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        _('username'),
        max_length=150,
    )
    email = models.EmailField(
        _('email address'),
        unique=True,
    )
    age = models.PositiveIntegerField(('Age'), default=0, blank=True)

    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(_('staff status'), default=False)
    is_active = models.BooleanField(_('active'), default=True)
    data_joined = models.DateTimeField(_('data joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        db_table = 'users'
        swappable = 'AUTH_USER_MODEL'

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

login_task/tasks/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()

    def __str__(self):
        return f'{self.title}, {self.content}'

login_task/accounts/forms.py
from .models import CustomUser
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('email', 'age')

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = (
        'username',
        'email',
        'age',
        )

login_task/tasks/forms.py
from django import forms


class TaskCreationForm(forms.Form):
    title = forms.CharField(label='Title', max_length=255)
    content = forms.CharField(label='Content', widget=forms.Textarea())

login_task/accounts/views.py
from django.urls import reverse_lazy, reverse
from django.contrib.auth import get_user_model, login, authenticate
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from .forms import UserUpdateForm
from .forms import CustomUserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin


User = get_user_model()

class OnlyYouMixin(UserPassesTestMixin):
    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser

class UserCreateAndLoginView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('tasks:index')

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get('username')
        raw_pw = form.cleaned_data.get('password1')
        email = form.cleaned_data.get('email')
        age = form.cleaned_data.get('age')
        user = authenticate(email=email, password=raw_pw)
        login(self.request, user)
        return response

class UserDetail(OnlyYouMixin, DetailView):
    model = User
    template_name = 'accounts/user_detail.html'

class UserUpdate(OnlyYouMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'accounts/user_edit.html'
    def get_success_url(self):
        return reverse('user_detail', kwargs={'pk': self.kwargs['pk']})

class PasswordChange(PasswordChangeView):
    template_name = 'accounts/password_change.html'

class PasswordChangeDone(PasswordChangeDoneView):
    template_name = 'accounts/user_detail.html'

class UserDelete(OnlyYouMixin, DeleteView):
    model = User
    template_name = 'accounts/user_delete.html'
    success_url = reverse_lazy('login')

login_task/tasks/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Task
from .forms import TaskCreationForm


def index(request):
    tasks = Task.objects.all()
    params = {
        'tasks': tasks,
    }
    return render(request, 'tasks/index.html', params)


def create(request):
    if (request.method == 'POST'):
        title = request.POST['title']
        content = request.POST['content']
        task = Task(title=title, content=content)
        task.save()
        return redirect('tasks:index')
    else:
        params = {
            'form': TaskCreationForm(),
        }
        return render(request, 'tasks/create.html', params)


def detail(request, task_id):
    task = Task.objects.get(id=task_id)
    params = {
        'task': task,
    }
    return render(request, 'tasks/detail.html', params)


def edit(request, task_id):
    task = Task.objects.get(id=task_id)
    if (request.method == 'POST'):
        task.title = request.POST['title']
        task.content = request.POST['content']
        task.save()
        return redirect('tasks:detail', task_id)
    else:
        form = TaskCreationForm(initial={
            'title': task.title,
            'content': task.content,
        })
        params = {
            'task': task,
            'form': form,
        }
        return render(request, 'tasks/edit.html', params)


def delete(request, task_id):
    task = Task.objects.get(id=task_id)
    if (request.method == 'POST'):
        task.delete()
        return redirect('tasks:index')
    else:
        params = {
            'task': task,
        }
        return render(request, 'tasks/delete.html', params)

login_task/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block main %}
<h1>Log In</h1>

<form method="post">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ next }}" />
  {{ form.as_p }}
  <input type="submit" value="Log In">
</form>
{% endblock %}

login_task/accounts/templates/accounts/password_change.html
{% extends "base.html" %}

{% block main %}
<form action="" method="POST">
  {{ form.as_p }}
  {% csrf_token %}
  <button type="submit">Change Password</button>
</form>
<a href="{% url 'user_detail' user.id %}">Back</a>
{% endblock %}

login_task/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block main %}
<h2>Member Registration</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Registration">
</form>
{% endblock %}

login_task/accounts/templates/accounts/user_delete.html
{% extends "base.html" %}

{% block main %}
<table>
  <tbody>
    <tr>
      <th>User Name</th>
      <td>{{ user.username }}</td>
    </tr>
    <tr>
      <th>Email</th>
      <td>{{ user.email }}</td>
    </tr>
    <tr>
      <th>Age</th>
      <td>{{ user.age }}</td>
    </tr>
  </tbody>
</table>

<form action="{% url 'user_delete' user.id %}" method="post">
  {% csrf_token %}
  <input type="submit" value="Delete">
</form>

<a href="{% url 'user_detail' user.id %}">Back</a>
{% endblock %}

login_task/accounts/templates/accounts/user_detail.html
{% extends "base.html" %}

{% block main %}
<table>
  <tbody>
    <tr>
      <th>Username: </th>
      <td>{{ user.username }}</td>
    </tr>
    <tr>
      <th>Email: </th>
      <td>{{ user.email }}</td>
    </tr>
    <tr>
      <th>Age: </th>
      <td>{{ user.age }}</td>
    </tr>
  </tbody>
</table>
<a href="{% url 'user_update' user.pk %}">Edit</a>
<a href="{% url 'password_change' %}">Change Password</a>
{% endblock %}

login_task/accounts/templates/accounts/user_edit.html
{% extends "base.html" %}

{% block main %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>
<a href="{% url 'user_detail' user.id %}">Back</a>
<a href="{% url 'user_delete' user.id %}">Delete</a>
{% endblock %}

login_task/tasks/templates/tasks/create.html
{% extends "base.html" %}

{% block main %}
<h1>Task Registration Page</h1>
<form action="{% url 'tasks:create' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create">
</form>

<br>

<a href="{% url 'tasks:index' %}">Back</a>
{% endblock %}

login_task/tasks/templates/tasks/delete.html
{% extends "base.html" %}

{% block main %}
<h1>Task Deletion Page</h1>
<p>
  <strong>Title:</strong>
  {{task.title}}
</p>

<p>
  <strong>Content:</strong>
  {{task.content}}
</p>
<form action="{% url 'tasks:delete' task.id %}" method="post">
  {% csrf_token %}
  <input type="submit" value="Delete">
</form>

<br>

<a href="{% url 'tasks:index' %}">Back</a>
{% endblock %}

login_task/tasks/templates/tasks/detail.html
{% extends "base.html" %}

{% block main %}
<h1>Task Details Page</h1>
<p>
  <strong>Title:</strong>
  {{task.title}}
</p>

<p>
  <strong>Content:</strong>
  {{task.content}}
</p>
<a href="{% url 'tasks:index' %}">Back</a> |
<a href="{% url 'tasks:edit' task.id %}">Edit</a>
{% endblock %}

login_task/tasks/templates/tasks/edit.html
{% extends "base.html" %}

{% block main %}
<h1>Task Edit Page</h1>
<form action="{% url 'tasks:edit' task.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>

<br>

<a href="{% url 'tasks:detail' task.id %}">Details</a> |
<a href="{% url 'tasks:index' %}">Back</a>

{% endblock %}

login_task/tasks/templates/tasks/index.html
{% extends "base.html" %}

{% block main %}
<h1>Task List Page</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th colspan="3"></th>
  </tr>
  {% for task in tasks %}
  <tr>
    <td>{{task.title}}</td>
    <td>{{task.content}}</td>
    <td><a href="{% url 'tasks:detail' task.id %}">Details</a></td>
    <td><a href="{% url 'tasks:edit' task.id %}">Edit</a></td>
    <td><a href="{% url 'tasks:delete' task.id %}">Delete</a></td>
  </tr>
  {% endfor %}
</table>

<br>

<a href="{% url 'tasks:create' %}">Create New</a>

{% endblock %}

login_task/templates/base.html
{% load static %}

<html>

  <head>
    <meta charset="utf-8">
    <title>Log In Assignment</title>
    <link rel="stylesheet" href="{% static 'tasks/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'tasks/css/style.css' %}">
  </head>

  <body>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'tasks:index' %}">Task List</a></li>
        <li><a href="{% url 'logout' %}">Log Out</a></li>
        <li><a href="{% url 'user_detail' user.pk %}">Account</a></li>
        {% else %}
        <li><a href="{% url 'login' %}">Log In</a></li>
        <li><a href="{% url 'signup' %}">Register</a></li>
        {% endif %}
      </ul>
    </nav>
    <main>
      <div>
        {% block main %}
        {% endblock %}
      </div>
    </main>
  </body>

</html>